DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'weges') THEN
        CREATE SCHEMA weges;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS weges."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Estabelecimentos" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Sigla" text NOT NULL,
    "Denominacao" text NOT NULL,
    "Morada" text NOT NULL,
    "Email" text NOT NULL,
    "Telefone" text NOT NULL,
    "TipoPrestador" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" text NOT NULL,
    CONSTRAINT "PK_Estabelecimentos" PRIMARY KEY ("Id")
);

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241114043245_init-mig', '9.0.4');

ALTER TABLE "Estabelecimentos" ALTER COLUMN "TipoPrestador" DROP NOT NULL;

ALTER TABLE "Estabelecimentos" ALTER COLUMN "Telefone" DROP NOT NULL;

ALTER TABLE "Estabelecimentos" ALTER COLUMN "Sigla" DROP NOT NULL;

ALTER TABLE "Estabelecimentos" ALTER COLUMN "Morada" DROP NOT NULL;

ALTER TABLE "Estabelecimentos" ALTER COLUMN "Email" DROP NOT NULL;

ALTER TABLE "Estabelecimentos" ADD "InicioAtividade" date NOT NULL DEFAULT DATE '-infinity';

CREATE TABLE "Entidades" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Denominacao" text,
    "Morada" text,
    "NifNipc" text NOT NULL,
    "Telefone" text,
    "Email" text,
    "Sigla" text,
    "NrERS" integer NOT NULL,
    "EmailNotificacoesERS" text,
    "EmailNotificacoesGerais" text,
    "CodCaeId" text,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" text NOT NULL,
    CONSTRAINT "PK_Entidades" PRIMARY KEY ("Id")
);

CREATE TABLE "CodCaes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Designacao" text NOT NULL,
    "EntidadeId" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" text NOT NULL,
    CONSTRAINT "PK_CodCaes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CodCaes_Entidades_EntidadeId" FOREIGN KEY ("EntidadeId") REFERENCES "Entidades" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CodCaes_EntidadeId" ON "CodCaes" ("EntidadeId");

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241126030356_aLotOfStuff', '9.0.4');

ALTER TABLE "Entidades" DROP COLUMN "CodCaeId";

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241126031031_codCaesM2M', '9.0.4');

ALTER TABLE "CodCaes" DROP CONSTRAINT "FK_CodCaes_Entidades_EntidadeId";

DROP INDEX "IX_CodCaes_EntidadeId";

ALTER TABLE "CodCaes" DROP COLUMN "EntidadeId";

CREATE TABLE "CodCaeEntidade" (
    "CodCaesId" bigint NOT NULL,
    "EntidadesId" bigint NOT NULL,
    CONSTRAINT "PK_CodCaeEntidade" PRIMARY KEY ("CodCaesId", "EntidadesId"),
    CONSTRAINT "FK_CodCaeEntidade_CodCaes_CodCaesId" FOREIGN KEY ("CodCaesId") REFERENCES "CodCaes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CodCaeEntidade_Entidades_EntidadesId" FOREIGN KEY ("EntidadesId") REFERENCES "Entidades" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CodCaeEntidade_EntidadesId" ON "CodCaeEntidade" ("EntidadesId");

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241126031340_codCaesM2M2', '9.0.4');

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241126234442_entidadeECodCae', '9.0.4');

ALTER TABLE "Estabelecimentos" ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE "Estabelecimentos" ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE "Entidades" ALTER COLUMN "Telefone" TYPE character varying(9);

ALTER TABLE "Entidades" ALTER COLUMN "Sigla" TYPE character varying(8);

ALTER TABLE "Entidades" ALTER COLUMN "NrERS" TYPE text;
ALTER TABLE "Entidades" ALTER COLUMN "NrERS" DROP NOT NULL;

ALTER TABLE "Entidades" ALTER COLUMN "NifNipc" TYPE character varying(9);

ALTER TABLE "Entidades" ALTER COLUMN "Morada" TYPE character varying(200);

ALTER TABLE "Entidades" ALTER COLUMN "ModifiedBy" DROP NOT NULL;
ALTER TABLE "Entidades" ALTER COLUMN "ModifiedBy" SET DEFAULT 'system-usr';

ALTER TABLE "Entidades" ALTER COLUMN "Modified" SET DEFAULT (NOW());

ALTER TABLE "Entidades" ALTER COLUMN "EmailNotificacoesGerais" TYPE character varying(50);

ALTER TABLE "Entidades" ALTER COLUMN "EmailNotificacoesERS" TYPE character varying(50);

ALTER TABLE "Entidades" ALTER COLUMN "Email" TYPE character varying(50);

ALTER TABLE "Entidades" ALTER COLUMN "Denominacao" TYPE character varying(200);

ALTER TABLE "Entidades" ALTER COLUMN "CreatedBy" DROP NOT NULL;
ALTER TABLE "Entidades" ALTER COLUMN "CreatedBy" SET DEFAULT 'system-usr';

ALTER TABLE "Entidades" ALTER COLUMN "Created" SET DEFAULT (NOW());

ALTER TABLE "CodCaes" ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE "CodCaes" ALTER COLUMN "CreatedBy" DROP NOT NULL;

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241127014602_configsEF', '9.0.4');

INSERT INTO "Entidades" ("Id", "Denominacao", "Email", "EmailNotificacoesERS", "EmailNotificacoesGerais", "Morada", "NifNipc", "NrERS", "Sigla", "Telefone")
VALUES (1, 'Teste 1', 'emailteste@email.email', 'emailnotificacoes@email.email', 'emailnotificacoes@email.email', 'Rua do Teste 1', '123123123', 'A-1234', 'TsT1', '921111111');
INSERT INTO "Entidades" ("Id", "Denominacao", "Email", "EmailNotificacoesERS", "EmailNotificacoesGerais", "Morada", "NifNipc", "NrERS", "Sigla", "Telefone")
VALUES (2, 'Teste 2', 'emailteste@email.email', 'emailnotificacoes@email.email', 'emailnotificacoes@email.email', 'Rua do Teste 2', '123123123', 'A-1234', 'TsT2', '921111111');

SELECT setval(
    pg_get_serial_sequence('"Entidades"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Entidades") + 1,
        nextval(pg_get_serial_sequence('"Entidades"', 'Id'))),
    false);

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241202221302_data', '9.0.4');

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241219111821_AddedIdentity', '9.0.4');

DROP TABLE "AspNetRoleClaims";

DROP TABLE "AspNetUserClaims";

DROP TABLE "AspNetUserLogins";

DROP TABLE "AspNetUserRoles";

DROP TABLE "AspNetUserTokens";

DROP TABLE "AspNetRoles";

DROP TABLE "AspNetUsers";

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'weges') THEN
        CREATE SCHEMA weges;
    END IF;
END $EF$;

ALTER TABLE "Estabelecimentos" SET SCHEMA weges;

ALTER TABLE "Entidades" SET SCHEMA weges;

ALTER TABLE "CodCaes" SET SCHEMA weges;

ALTER TABLE "CodCaeEntidade" SET SCHEMA weges;

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241227221456_UsersInit', '9.0.4');

UPDATE weges."Entidades" SET "Denominacao" = 'Entidade 1', "Sigla" = 'ent1'
WHERE "Id" = 1;

UPDATE weges."Entidades" SET "Denominacao" = 'Entidade 2', "Sigla" = 'ent2'
WHERE "Id" = 2;

INSERT INTO weges."Estabelecimentos" ("Id", "Created", "CreatedBy", "Denominacao", "Email", "InicioAtividade", "Modified", "ModifiedBy", "Morada", "Sigla", "Telefone", "TipoPrestador")
VALUES (1, TIMESTAMPTZ '-infinity', NULL, 'Estabelecimento 1', 'email@email.email', DATE '2020-02-20', TIMESTAMPTZ '-infinity', NULL, 'estab 1 morada', 'estab1', '291111111', 'Tipo de Prestador');
INSERT INTO weges."Estabelecimentos" ("Id", "Created", "CreatedBy", "Denominacao", "Email", "InicioAtividade", "Modified", "ModifiedBy", "Morada", "Sigla", "Telefone", "TipoPrestador")
VALUES (2, TIMESTAMPTZ '-infinity', NULL, 'Estabelecimento 2', 'email@email.email', DATE '2023-02-20', TIMESTAMPTZ '-infinity', NULL, 'estab 2 morada', 'estab2', '291111112', 'Tipo de Prestador');

SELECT setval(
    pg_get_serial_sequence('weges."Estabelecimentos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM weges."Estabelecimentos") + 1,
        nextval(pg_get_serial_sequence('weges."Estabelecimentos"', 'Id'))),
    false);

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250101205630_AddedEstabsExemplo', '9.0.4');

CREATE TABLE weges."DirecoesClinicas" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text,
    "Cargo" text,
    "Identificacao" text,
    "ValidadeIdentificacao" date NOT NULL,
    "Cedula" text,
    "Ordem" text,
    "Especialidade" text,
    "EspecialidadeId" bigint NOT NULL,
    "Observacoes" text,
    "EstabelecimentoId" bigint NOT NULL,
    "TipologiaId" bigint NOT NULL,
    "Tipologia" text,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" text,
    CONSTRAINT "PK_DirecoesClinicas" PRIMARY KEY ("Id")
);

INSERT INTO weges."DirecoesClinicas" ("Id", "Cargo", "Cedula", "Created", "CreatedBy", "Especialidade", "EspecialidadeId", "EstabelecimentoId", "Identificacao", "Modified", "ModifiedBy", "Nome", "Observacoes", "Ordem", "Tipologia", "TipologiaId", "ValidadeIdentificacao")
VALUES (1, 'Cargo 1', 'Cedula 1', TIMESTAMPTZ '-infinity', NULL, 'Especialidade 1', 1, 1, 'Identificacao 1', TIMESTAMPTZ '-infinity', NULL, 'Nome 1', 'Observacoes 1', 'Ordem 1', 'Tipologia 1', 1, DATE '2023-02-20');
INSERT INTO weges."DirecoesClinicas" ("Id", "Cargo", "Cedula", "Created", "CreatedBy", "Especialidade", "EspecialidadeId", "EstabelecimentoId", "Identificacao", "Modified", "ModifiedBy", "Nome", "Observacoes", "Ordem", "Tipologia", "TipologiaId", "ValidadeIdentificacao")
VALUES (2, 'Cargo 2', 'Cedula 2', TIMESTAMPTZ '-infinity', NULL, 'Especialidade 2', 2, 2, 'Identificacao 2', TIMESTAMPTZ '-infinity', NULL, 'Nome 2', 'Observacoes 2', 'Ordem 2', 'Tipologia 2', 2, DATE '2023-02-20');

SELECT setval(
    pg_get_serial_sequence('weges."DirecoesClinicas"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM weges."DirecoesClinicas") + 1,
        nextval(pg_get_serial_sequence('weges."DirecoesClinicas"', 'Id'))),
    false);

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250101211436_AddedDirecaoClinicaExemplo', '9.0.4');

DELETE FROM weges."DirecoesClinicas"
WHERE "Id" = 1;

DELETE FROM weges."DirecoesClinicas"
WHERE "Id" = 2;

DELETE FROM weges."Entidades"
WHERE "Id" = 1;

DELETE FROM weges."Entidades"
WHERE "Id" = 2;

DELETE FROM weges."Estabelecimentos"
WHERE "Id" = 1;

DELETE FROM weges."Estabelecimentos"
WHERE "Id" = 2;

ALTER TABLE weges."DirecoesClinicas" DROP COLUMN "Tipologia";

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "TipoPrestador" TYPE character varying(100);

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Telefone" TYPE character varying(50);

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Sigla" TYPE character varying(50);

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Morada" TYPE character varying(512);

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "ModifiedBy" SET DEFAULT 'system-usr';

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Modified" SET DEFAULT (NOW());

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Email" TYPE character varying(255);

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Denominacao" TYPE character varying(255);

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "CreatedBy" SET DEFAULT 'system-usr';

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Created" SET DEFAULT (NOW());

ALTER TABLE weges."Estabelecimentos" ADD "AlvaraId" bigint;

ALTER TABLE weges."Estabelecimentos" ADD "CartaoNipcId" bigint;

ALTER TABLE weges."Estabelecimentos" ADD "DireitosDeveresId" bigint;

ALTER TABLE weges."Estabelecimentos" ADD "FicheirosAnexarId" bigint;

ALTER TABLE weges."Estabelecimentos" ADD "LicenciamentoRegistoLegalId" bigint;

ALTER TABLE weges."Estabelecimentos" ADD "ListaVerificacaoId" bigint;

ALTER TABLE weges."Estabelecimentos" ADD "MedidaAnpcId" bigint;

ALTER TABLE weges."Estabelecimentos" ADD "ParecerAnpcId" bigint;

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "TipologiaId" DROP NOT NULL;

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "ModifiedBy" SET DEFAULT 'system-usr';

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "Modified" SET DEFAULT (NOW());

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "CreatedBy" SET DEFAULT 'system-usr';

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "Created" SET DEFAULT (NOW());

CREATE TABLE weges."AnexoTipos" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Tipo" character varying(100) NOT NULL,
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_AnexoTipos" PRIMARY KEY ("Id")
);

CREATE TABLE weges."ColaboradorTipo" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Tipo" text NOT NULL,
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_ColaboradorTipo" PRIMARY KEY ("Id")
);

CREATE TABLE weges."Ficheiros" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(255),
    "Localizacao" character varying(512),
    "Tipo" character varying(100),
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_Ficheiros" PRIMARY KEY ("Id")
);

CREATE TABLE weges."Tipologias" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" text,
    CONSTRAINT "PK_Tipologias" PRIMARY KEY ("Id")
);

CREATE TABLE weges."Anexos" (
    "Id" bigint NOT NULL,
    "Nome" character varying(255) NOT NULL,
    "Submetido" date NOT NULL,
    "Observacoes" character varying(1000),
    "FicheiroId" bigint NOT NULL,
    "AnexoTipoId" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "Modified" timestamp with time zone NOT NULL,
    "ModifiedBy" text,
    CONSTRAINT "PK_Anexos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Anexos_AnexoTipos_AnexoTipoId" FOREIGN KEY ("AnexoTipoId") REFERENCES weges."AnexoTipos" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Anexos_Estabelecimentos_Id" FOREIGN KEY ("Id") REFERENCES weges."Estabelecimentos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Anexos_Ficheiros_FicheiroId" FOREIGN KEY ("FicheiroId") REFERENCES weges."Ficheiros" ("Id") ON DELETE CASCADE
);

CREATE TABLE weges."CertificadosERS" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Periodo" text,
    "NrCertificado" text,
    "DataSubmissao" date,
    "DataExpiracao" date,
    "Observacoes" text,
    "DataExpiracaoTaxa" date,
    "DataPagamentoTaxa" date,
    "EstabelecimentoId" bigint NOT NULL,
    "FicheiroId" bigint,
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_CertificadosERS" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CertificadosERS_Estabelecimentos_EstabelecimentoId" FOREIGN KEY ("EstabelecimentoId") REFERENCES weges."Estabelecimentos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CertificadosERS_Ficheiros_FicheiroId" FOREIGN KEY ("FicheiroId") REFERENCES weges."Ficheiros" ("Id") ON DELETE SET NULL
);

CREATE TABLE weges."LicencasERS" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "NrLicenca" text,
    "DataSubmissao" date,
    "Observacoes" text,
    "EstabelecimentoId" bigint NOT NULL,
    "FicheiroId" bigint,
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_LicencasERS" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LicencasERS_Estabelecimentos_EstabelecimentoId" FOREIGN KEY ("EstabelecimentoId") REFERENCES weges."Estabelecimentos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LicencasERS_Ficheiros_FicheiroId" FOREIGN KEY ("FicheiroId") REFERENCES weges."Ficheiros" ("Id") ON DELETE SET NULL
);

CREATE TABLE weges."Servicos" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text,
    "DataInicio" date,
    "Responsavel" text,
    "Horario" text,
    "Observacoes" text,
    "TipologiaId" bigint,
    "EstabelecimentoId" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_Servicos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Servicos_Tipologias_TipologiaId" FOREIGN KEY ("TipologiaId") REFERENCES weges."Tipologias" ("Id") ON DELETE SET NULL
);

CREATE TABLE weges."Colaboradores" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "NrIdentificacao" text NOT NULL,
    "DataNascimento" date NOT NULL,
    "InicioAtividade" date NOT NULL,
    "Cedula" text NOT NULL,
    "Especialidade" text NOT NULL,
    "Estado" boolean NOT NULL,
    "TotalHoras" integer NOT NULL,
    "Observacoes" text NOT NULL,
    "ServicoId" bigint NOT NULL,
    "EstabelecimentoId" bigint NOT NULL,
    "ColaboradorTipoId" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_Colaboradores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Colaboradores_ColaboradorTipo_ColaboradorTipoId" FOREIGN KEY ("ColaboradorTipoId") REFERENCES weges."ColaboradorTipo" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Colaboradores_Estabelecimentos_EstabelecimentoId" FOREIGN KEY ("EstabelecimentoId") REFERENCES weges."Estabelecimentos" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Colaboradores_Servicos_ServicoId" FOREIGN KEY ("ServicoId") REFERENCES weges."Servicos" ("Id") ON DELETE CASCADE
);

CREATE TABLE weges."Formacao" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "HorasFormacao" integer NOT NULL,
    "Data" date NOT NULL,
    "Observacoes" text,
    "ColaboradorId" bigint,
    "Created" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" text DEFAULT 'system-usr',
    "Modified" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ModifiedBy" text DEFAULT 'system-usr',
    CONSTRAINT "PK_Formacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Formacao_Colaboradores_ColaboradorId" FOREIGN KEY ("ColaboradorId") REFERENCES weges."Colaboradores" ("Id")
);

CREATE INDEX "IX_Estabelecimentos_AlvaraId" ON weges."Estabelecimentos" ("AlvaraId");

CREATE INDEX "IX_Estabelecimentos_CartaoNipcId" ON weges."Estabelecimentos" ("CartaoNipcId");

CREATE INDEX "IX_Estabelecimentos_DireitosDeveresId" ON weges."Estabelecimentos" ("DireitosDeveresId");

CREATE INDEX "IX_Estabelecimentos_FicheirosAnexarId" ON weges."Estabelecimentos" ("FicheirosAnexarId");

CREATE INDEX "IX_Estabelecimentos_ListaVerificacaoId" ON weges."Estabelecimentos" ("ListaVerificacaoId");

CREATE INDEX "IX_Estabelecimentos_MedidaAnpcId" ON weges."Estabelecimentos" ("MedidaAnpcId");

CREATE INDEX "IX_Estabelecimentos_ParecerAnpcId" ON weges."Estabelecimentos" ("ParecerAnpcId");

CREATE INDEX "IX_DirecoesClinicas_TipologiaId" ON weges."DirecoesClinicas" ("TipologiaId");

CREATE INDEX "IX_Anexos_AnexoTipoId" ON weges."Anexos" ("AnexoTipoId");

CREATE INDEX "IX_Anexos_FicheiroId" ON weges."Anexos" ("FicheiroId");

CREATE UNIQUE INDEX "IX_CertificadosERS_EstabelecimentoId" ON weges."CertificadosERS" ("EstabelecimentoId");

CREATE INDEX "IX_CertificadosERS_FicheiroId" ON weges."CertificadosERS" ("FicheiroId");

CREATE INDEX "IX_Colaboradores_ColaboradorTipoId" ON weges."Colaboradores" ("ColaboradorTipoId");

CREATE INDEX "IX_Colaboradores_EstabelecimentoId" ON weges."Colaboradores" ("EstabelecimentoId");

CREATE INDEX "IX_Colaboradores_ServicoId" ON weges."Colaboradores" ("ServicoId");

CREATE INDEX "IX_Formacao_ColaboradorId" ON weges."Formacao" ("ColaboradorId");

CREATE UNIQUE INDEX "IX_LicencasERS_EstabelecimentoId" ON weges."LicencasERS" ("EstabelecimentoId");

CREATE INDEX "IX_LicencasERS_FicheiroId" ON weges."LicencasERS" ("FicheiroId");

CREATE INDEX "IX_Servicos_TipologiaId" ON weges."Servicos" ("TipologiaId");

ALTER TABLE weges."DirecoesClinicas" ADD CONSTRAINT "FK_DirecoesClinicas_Tipologias_TipologiaId" FOREIGN KEY ("TipologiaId") REFERENCES weges."Tipologias" ("Id") ON DELETE SET NULL;

ALTER TABLE weges."Estabelecimentos" ADD CONSTRAINT "FK_Estabelecimentos_Anexos_AlvaraId" FOREIGN KEY ("AlvaraId") REFERENCES weges."Anexos" ("Id");

ALTER TABLE weges."Estabelecimentos" ADD CONSTRAINT "FK_Estabelecimentos_Anexos_CartaoNipcId" FOREIGN KEY ("CartaoNipcId") REFERENCES weges."Anexos" ("Id");

ALTER TABLE weges."Estabelecimentos" ADD CONSTRAINT "FK_Estabelecimentos_Anexos_DireitosDeveresId" FOREIGN KEY ("DireitosDeveresId") REFERENCES weges."Anexos" ("Id");

ALTER TABLE weges."Estabelecimentos" ADD CONSTRAINT "FK_Estabelecimentos_Anexos_FicheirosAnexarId" FOREIGN KEY ("FicheirosAnexarId") REFERENCES weges."Anexos" ("Id");

ALTER TABLE weges."Estabelecimentos" ADD CONSTRAINT "FK_Estabelecimentos_Anexos_ListaVerificacaoId" FOREIGN KEY ("ListaVerificacaoId") REFERENCES weges."Anexos" ("Id");

ALTER TABLE weges."Estabelecimentos" ADD CONSTRAINT "FK_Estabelecimentos_Anexos_MedidaAnpcId" FOREIGN KEY ("MedidaAnpcId") REFERENCES weges."Anexos" ("Id");

ALTER TABLE weges."Estabelecimentos" ADD CONSTRAINT "FK_Estabelecimentos_Anexos_ParecerAnpcId" FOREIGN KEY ("ParecerAnpcId") REFERENCES weges."Anexos" ("Id");

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250212005433_AnexosFicheiro', '9.0.4');

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "ValidadeIdentificacao" TYPE timestamp with time zone;

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250227023959_ChangeDateTypes', '9.0.4');

ALTER TABLE weges."Servicos" ALTER COLUMN "DataInicio" TYPE timestamp with time zone;

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250227024254_ChangeDateTypes2', '9.0.4');

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataSubmissao" TYPE timestamp with time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataPagamentoTaxa" TYPE timestamp with time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataExpiracaoTaxa" TYPE timestamp with time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataExpiracao" TYPE timestamp with time zone;

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250227235337_ChangeDateTimesCertificadoErs', '9.0.4');

ALTER TABLE weges."Tipologias" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Tipologias" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."Servicos" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Servicos" ALTER COLUMN "DataInicio" TYPE timestamp without time zone;

ALTER TABLE weges."Servicos" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."LicencasERS" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."LicencasERS" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."Formacao" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Formacao" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."Ficheiros" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Ficheiros" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Estabelecimentos" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."Entidades" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Entidades" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "ValidadeIdentificacao" TYPE timestamp without time zone;

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."DirecoesClinicas" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."ColaboradorTipo" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."ColaboradorTipo" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."Colaboradores" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Colaboradores" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."CodCaes" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."CodCaes" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataSubmissao" TYPE timestamp without time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataPagamentoTaxa" TYPE timestamp without time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataExpiracaoTaxa" TYPE timestamp without time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "DataExpiracao" TYPE timestamp without time zone;

ALTER TABLE weges."CertificadosERS" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."AnexoTipos" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."AnexoTipos" ALTER COLUMN "Created" TYPE timestamp without time zone;

ALTER TABLE weges."Anexos" ALTER COLUMN "Modified" TYPE timestamp without time zone;

ALTER TABLE weges."Anexos" ALTER COLUMN "Created" TYPE timestamp without time zone;

INSERT INTO weges."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250228003446_FixedDateTimes', '9.0.4');

COMMIT;

