name: weges-api-image

on:
  push:
    branches: [ "main" ]
    paths: [ "ApiService/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "ApiService/**" ]

jobs:

  build:
    
    runs-on: home-runner
    permissions:
      contents: write
      packages: write
      actions: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js (for versioning tool)
      uses: actions/setup-node@v4

    - name: Install Standard Version
      run: npm install -g standard-version
      
    - name: Determine New Version
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        COMPONENT=api # or frontend

        # Fetch all tags from remote first
        git fetch --tags

        # Configure standard-version to use the prefix
        echo "{\"tagPrefix\":\"$COMPONENT-v\"}" > .versionrc

        # Run standard-version to bump version, commit and tag
        npx standard-version --no-verify --commit-all

        # Find the latest tag for this component
        LATEST_TAG=$(git tag --list "$COMPONENT-v*" --sort=-v:refname | head -n 1)

        if [ -z "$LATEST_TAG" ]; then
          NEW_VERSION="$COMPONENT-v1.0.0"
        else
          NEW_VERSION="$LATEST_TAG"
        fi

        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "New version: $NEW_VERSION"

        # Determine where to push based on GitHub environment
        if [[ "$GITHUB_REF" == refs/pull/* ]]; then
          echo "Running in pull request context. Will push to the base branch."
          # For pull requests, we need to push to the base branch
          # Extract PR number from GITHUB_REF
          PR_NUMBER=$(echo $GITHUB_REF | cut -d/ -f3)
          # Get the base branch from GITHUB_BASE_REF
          TARGET_BRANCH=$GITHUB_BASE_REF
        else
          # For direct pushes to branches
          TARGET_BRANCH=${GITHUB_REF#refs/heads/}
        fi

        echo "Pushing to branch: $TARGET_BRANCH"

        # Try the push with the correct branch
        git push origin HEAD:$TARGET_BRANCH --follow-tags
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build the Docker image
      run: docker build -t ghcr.io/mmpmendes/weges-v2/weges-api:$VERSION -f ApiService/Dockerfile . 

    - name: Tag the Docker image
      run: docker tag ghcr.io/mmpmendes/weges-v2/weges-api:$VERSION ghcr.io/mmpmendes/weges-v2/weges-api:latest

      
    - name: Push Docker Image to Github
      run: |
        docker push ghcr.io/mmpmendes/weges-v2/weges-api:$VERSION
        docker push ghcr.io/mmpmendes/weges-v2/weges-api:latest
    
    - name: Remove running container
      run: |
        docker rm -f weges-api-service

    - name: Deploy WebApi
      env: # Or as an environment variable
        api_address: ${{ secrets.API_ADDRESS }}
        connString: ${{ secrets.CONNECTIONSTRING }}
        port: ${{ secrets.PORT }}

      run: |
        docker run -d --name weges-api-service -e "ConnectionStrings:weges=$connString"  --restart unless-stopped --network traefik-net -l "traefik.enable=true" -l "traefik.http.routers.wegesapi.middlewares=corsheader@file" -l "traefik.http.routers.wegesapi.rule=Host($api_address)" -l "traefik.http.services.wegesapi.loadbalancer.server.port=$port" -l "traefik.http.routers.wegesapi.tls.certresolver=letsencrypt" -l "traefik.http.routers.wegesapi.tls=true" ghcr.io/mmpmendes/weges-v2/weges-api:latest   