name: weges-web-image

on:
  push:
    branches: [ "main" ]
    paths: [ "Identity/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Identity/**" ]

jobs:

  build:
    
    runs-on: home-runner
    permissions:
      contents: write
      packages: write
      actions: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js (for versioning tool)
      uses: actions/setup-node@v4

    - name: Install Standard Version
      run: npm install -g standard-version
      
    - name: Determine New Version
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        COMPONENT=webapp # or frontend
        
        # Fetch all tags from remote first
        git fetch --tags

        # Configure standard-version to use the prefix
        echo "{\"tagPrefix\":\"$COMPONENT-v\"}" > .versionrc

        # Run standard-version to bump version, commit and tag
        npx standard-version --no-verify --commit-all

        # Find the latest tag for this component
        LATEST_TAG=$(git tag --list "$COMPONENT-v*" --sort=-v:refname | head -n 1)
        if [ -z "$LATEST_TAG" ]; then
          NEW_VERSION="$COMPONENT-v1.0.0"
        else
          NEW_VERSION="$LATEST_TAG"
        fi

        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "New version: $NEW_VERSION"

        # Get the current branch name from GitHub context
        if [[ "$GITHUB_REF" == refs/pull/* ]]; then
          echo "Running in pull request context. Will push to the base branch."
          TARGET_BRANCH=$GITHUB_BASE_REF
        else
          TARGET_BRANCH=${GITHUB_REF#refs/heads/}
        fi

        echo "Pushing to branch: $TARGET_BRANCH"

        # Reset to match remote but keep the changes as uncommitted
        git fetch origin $TARGET_BRANCH
        git reset --soft origin/$TARGET_BRANCH

        # Re-add all changes
        git add .

        # Commit again with the same message
        CURRENT_VERSION=${NEW_VERSION#$COMPONENT-v}
        git commit -m "chore(release): $COMPONENT-v$CURRENT_VERSION"

        # Re-tag
        git tag -d $NEW_VERSION  # Delete the existing tag
        git tag $NEW_VERSION     # Re-create it at the new position

        # Now push
        git push origin HEAD:$TARGET_BRANCH --follow-tags
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build the Docker image
      run: docker build -t ghcr.io/mmpmendes/weges-v2/weges-app:$VERSION -f Identity/Dockerfile . 

    - name: Tag the Docker image
      run: docker tag ghcr.io/mmpmendes/weges-v2/weges-app:$VERSION ghcr.io/mmpmendes/weges-v2/weges-app:latest

      
    - name: Push Docker Image to Github
      run: |
        docker push ghcr.io/mmpmendes/weges-v2/weges-app:$VERSION
        docker push ghcr.io/mmpmendes/weges-v2/weges-app:latest
    
    - name: Remove running container
      run: |
        docker rm -f weges-app

    - name: Deploy WebApp
      env: # Or as an environment variable
        web_address: ${{ secrets.DEV_PAGE_ADDRESS }}
        api_address: ${{ secrets.API_ADDRESS }}
        connString: ${{ secrets.CONNECTIONSTRING }}
        gClientId: ${{ secrets.GOOGLE_CLIENTID }}
        gClientSecret: ${{ secrets.GOOGLE_CLIENTSECRET }}
        emailHost: ${{ secrets.EMAILHOST }}
        emailUser: ${{ secrets.EMAILUSER }}
        emailPassword: ${{ secrets.EMAILPASSWORD }}
        emailPort: ${{ secrets.EMAILPORT }}
        adminEmail: ${{ secrets.ADMINEMAIL }}
        adminPassword: ${{ secrets.ADMINPASSWORD }}
      run: |
          docker run -d --name weges-app -e "ConnectionStrings:weges=$connString" -e "GoogleClientId=$gClientId" -e "GoogleClientSecret=$gClientSecret" -e "EmailConfiguracoes=$emailUser" -e "EmailConfiguracoes:Name=WEGES" -e "EmailConfiguracoes:Host=$emailHost" -e "EmailConfiguracoes:UserName=$emailUser" -e "EmailConfiguracoes:Password=$emailPassword" -e "adminEmail=$adminEmail" -e "adminPassword=$adminPassword" -e "services__apiservice__https__0=$api_address" --restart unless-stopped --network traefik-net -l "traefik.enable=true" -l "traefik.http.routers.wegesapp.tls=true" -l "traefik.http.routers.wegesapp.rule=Host($web_address)" -l "traefik.http.routers.wegesapp.tls.certresolver=letsencrypt" -l "traefik.http.routers.wegesapp.tls=true" ghcr.io/mmpmendes/weges-v2/weges-app:latest